branch-defaults:
  master:
    environment: evolve-backend-elastic-dev
    group_suffix: null
global:
  application_name: evolve-backend
  branch: null
  default_ec2_keyname: ssh-key-3
  default_platform: node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
